apiVersion: apps/v1
kind: Deployment
metadata:
  name: hb-web-deployment
  labels:
    app: hb-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hb-web-app
  template:
    metadata:
      labels:
        app: hb-web-app
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: hb-my-sql-service
spec:
  selector:
    app.kubernetes.io/name: hb-web-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 3306
